Chore/upgrade polkadot v1.3.0 to v1.4.0 issue 1798
frequency-chain/frequency pull request #2024
Opened 2024-06-13 00:14 UTC by enddynayn

# Goal
The goal of this PR is 

Closes 

# Discussion

# Checklist
- [ ] Chain spec updated
- [ ] Custom RPC OR Runtime API added/changed? Updated js/api-augment.
- [ ] Design doc(s) updated
- [ ] Tests added
- [ ] Benchmarks added
- [ ] Weights updated

2024-06-13 00:17 UTC, enddynayn commented on node/service/src/chain_spec/frequency.rs
> +	).with_id(
with_protocol_id

2024-06-13 00:18 UTC, enddynayn commented on node/service/src/chain_spec/frequency_paseo.rs
> +	.with_id("frequency-paseo-local")
with_protocol_id

2024-06-13 00:20 UTC, enddynayn commented on node/service/src/chain_spec/frequency_rococo.rs
> +	.with_id("frequency-rococo-local")
with_protocol_id

2024-06-13 19:32 UTC, enddynayn commented on node/service/src/chain_spec/frequency_dev.rs
> +	// Name
rm

2024-06-17 13:24 UTC, wilwade requested changes
Nice update. One fix, one optional fix, and a separate thought.

2024-06-17 16:11 UTC, enddynayn commented on runtime/frequency/src/lib.rs
> +	type DmpQueue = frame_support::traits::EnqueueWithOrigin<(), sp_core::ConstU8<0>>;
I thought the same. However, EnqueueWithOrigin is not implemented on ().

2024-06-17 16:12 UTC, enddynayn commented on node/service/Cargo.toml
> +serde_json = { worspace = true }
Thats weird. I would expect this mistake to cause an error.

2024-06-17 16:24 UTC, wilwade commented on node/service/Cargo.toml
> +serde_json = { worspace = true }
It threw a warning only for me, but with a note that it would be an error in the future.

2024-06-17 16:25 UTC, wilwade approved these changes
Working for me!

- Review
- Local run

2024-06-17 20:37 UTC, saraswatpuneet approved these changes
* read through the code changes
* Checked correctness of chain spec builders 
🚢

2024-06-17 22:32 UTC, aramikm approved these changes
Looks good to me!

2024-06-17 22:32 UTC, merged

2024-06-17 22:47 UTC, enddynayn commented on Cargo.toml
> +parachain-info = { package = "staging-parachain-info", git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.4.0", default-features = false }
They renamed the package.

2024-06-17 22:56 UTC, aramikm commented on Cargo.toml
> +parachain-info = { package = "staging-parachain-info", git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.4.0", default-features = false }
having `staging` in the name is a bit confusing, specially since it's about parachains

2024-06-17 22:57 UTC, mattheworris reviewed
- Read through changes
- Interesting changes to the genesis build
Nice work!

2024-06-18 16:14 UTC, enddynayn commented on Cargo.toml
> +parachain-info = { package = "staging-parachain-info", git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.4.0", default-features = false }
I agree. It seems a bit odd choice of name.